#!python
Import('env idir_lib idir_prefix jinclude')
if "CXXFLAGS" in env['ENV']:
	cxxflags=env['ENV']['CXXFLAGS']
else:
	cxxflags=""
if "LD_LIBRARY_PATH" in env['ENV']:
	ld_lib_path=env['ENV']['LD_LIBRARY_PATH']
else:
	ld_lib_path=""
cxxflags=cxxflags+' -std=c++0x -Wall'
env.Append(CXXFLAGS = cxxflags)
env.Append(LD_LIBRARY_PATH = ld_lib_path)
env.Append(CPPPATH = [idir_prefix+'/include/jellyfish-2.2.10/'])
env.Append(CPPPATH = [jinclude])
cmasker = env.Program(target = '../bin/cmasker', source = ["masker.cc"], LIBS=['jellyfish-2.0', 'pthread'], LIBPATH = [ld_lib_path, idir_lib])
#env.Install('../bin', cmasker)
env.Alias('build',cmasker)
