#!python
Import('env idir_lib idir_prefix jinclude jlib')
if "GXX" in env['ENV']:
	env.Replace(CXX = env['ENV']['GXX'])
if "CXXFLAGS" in env['ENV']:
	cxxflags=env['ENV']['CXXFLAGS']
else:
	cxxflags=""
if "LD_LIBRARY_PATH" in env['ENV']:
	ld_lib_path=env['ENV']['LD_LIBRARY_PATH']
else:
	ld_lib_path=""
cxxflags=cxxflags+' -std=c++0x -Wall'
env.Append(CXXFLAGS = cxxflags)
env.Append(LD_LIBRARY_PATH = [ld_lib_path, jlib])
env.Append(CPPPATH = [idir_prefix+'/include/jellyfish-2.2.10/'])
env.Append(CPPPATH = [jinclude])
cmasker = env.Program(target = 'cmasker', source = ["masker.cc"], LIBS=['jellyfish-2.0', 'pthread'], LIBPATH = [ld_lib_path, idir_lib, jlib])
env.Precious('cmasker')
install_cmasker=env.Install(idir_prefix+'/bin', cmasker)
build=env.Alias("build", [cmasker])
env.Alias("install", [install_cmasker, build])
